import { projects } from "../data/projects";
function Header(){return <header className="header"><div className="shell headerInner"><a className="monogram" href="#top" aria-label="В начало">ЕТ</a><nav aria-label="Основная навигация"><a href="#work">Кейсы</a><a href="#about">Обо мне</a><a href="/cv.pdf" download>Скачать CV</a><a href="#telegram">Телеграм</a></nav></div></header>}
function Hero(){return <section className="hero shell" id="top"><div className="heroPortrait" role="img" aria-label="Фотография Егора Трещева"><span>Photo<br/>1:1</span></div><div className="heroTitle" id="about"><h1>Егор Трещев</h1><p>Продуктовый дизайнер в Альфа-Банке, ex. Pinkman, Cs.Money, Mkws</p></div><a className="telegramButton" id="telegram" href="#telegram">Написать в телеграм</a></section>}
function ProjectVisual({tone}:{tone:string}){return <div className={`projectVisual ${tone}`} aria-label="Изображение проекта"><span className="visualLabel">Project preview</span>{tone==="red"&&<><div className="phone"><div className="status"/><b>2 450 000 ₽</b><span>Сумма кредита</span><i/></div><div className="loanStat"><small>Ежемесячный платёж</small><strong>41 800 ₽</strong></div></>}{tone==="silver"&&<div className="browserMock"><div className="browserTop"/><div className="browserBody"><span>Кредит наличными</span><strong>Решение за 2 минуты</strong><button>Заполнить анкету</button></div></div>}{tone==="ink"&&<><div className="systemGrid"><span>Input</span><span>Step 03/05</span><b>Компоненты,<br/>которые говорят<br/>на одном языке</b></div><div className="tokens">08 px&nbsp;&nbsp; 16 px&nbsp;&nbsp; 24 px</div></>}{tone==="music"&&<><div className="album"><span>МТС</span><b>В пути</b><small>для автомобиля</small></div><div className="player"><span>Сейчас играет</span><strong>Evening drive</strong><div>━━●━━━━</div></div></>}</div>}
function SelectedWork(){return <section className="workSection shell" id="work" aria-label="Проекты"><div className="projects">{projects.map(p=><article className={`project project-${p.n}`} key={p.n}><a href={p.href} aria-label={`Открыть кейс: ${p.title}`}><ProjectVisual tone={p.tone}/><div className="projectCopy"><h3>{p.title}</h3><p>{p.meta}</p></div></a></article>)}</div></section>}
function Experiments(){return <section className="section experiments shell" id="concepts"><div className="sectionHead"><div><h2>Концепты</h2><p className="lead">Интерфейсы, идеи и визуальные эксперименты, которые не стали отдельными кейсами.</p></div></div><div className="gallery"><div className="experiment expA"><span>Dashboard study</span><div className="chart">64<small>%</small></div></div><div className="experiment expB"><span>Mobile banking</span><div className="miniPhone"><b>42 350 ₽</b><i/><i/><i/></div></div><div className="experiment expC"><span>Typography / 01</span><b>Аа</b></div><div className="experiment expD"><span>Widget</span><div className="weather">+18°<small>Москва</small></div></div><div className="experiment expE"><span>Product concept</span><div><b>Focus</b><p>12 tasks completed</p></div></div></div></section>}
function Outside(){return <section className="section outside shell" id="outside"><div className="sectionHead"><h2>Увлечения</h2></div><div className="outsideGrid"><article className="hobby coffee"><div className="photoPlaceholder"><span>Photo · coffee</span><div className="cup"/></div><h3>Кофе</h3><p>Люблю кофе и веду о нём Telegram-канал.</p><a href="#coffee-channel">Канал о кофе</a></article><article className="hobby padel"><div className="photoPlaceholder"><span>Photo · padel</span><div className="court"/></div><h3>Padel</h3><p>Играю в падел.</p></article><article className="hobby books"><div className="bookStack"><i/><i/><i/><span>Photo · books</span></div><h3>Books</h3><p>Читаю книги, иногда пишу о них на vc и Дзене.</p><div className="textLinks"><a href="#vc">vc</a><a href="#dzen">Дзен</a></div></article></div></section>}
function Footer(){return <footer className="footer"><div className="shell footerInner"><p>© Егор Трещев 2026</p><div><a href="mailto:hello@example.com">E-mail</a><a href="#telegram">Telegram</a><a href="/cv.pdf" download>Скачать CV</a></div></div></footer>}
export default function Home(){return <><Header/><main><Hero/><SelectedWork/><Experiments/><Outside/></main><Footer/></>}
