const cases = [
  { image: "Case1.png", title: "Анкета на кредит в мобильном приложении Альфа-Банка", href: "/credit-redesign" },
  { image: "Case3.png", title: "Приложение МТС Музыки для автомобиля", href: "/mts-music" },
  { image: "cs-money-thumb.png", title: "Редизайн сайта Cs.Money", href: "/cs-money" },
  { image: "Case4.png", title: "Лидирование дизайн-системы анкет сайта Альфа-Банка", href: "/form-design-system" },
] as const;

const conceptColumns = [["Pic1.png", "Pic4.png", "Pic8.png", "Pic9.png"], ["Pic2.png", "Pic5.png", "Pic7.png", "Pic10.png"], ["Pic3.png", "Pic6.png", "Pic11.png"]];

function DesktopHeader() { return <header className="deskHeader deskShell"><nav><a href="#work">Кейсы</a><a href="#hobbies">Обо мне</a></nav><nav><a href="/cv.pdf" download>Скачать CV</a><a href="https://t.me/yegortreschev" target="_blank" rel="noreferrer">Телеграм</a></nav></header> }

function DesktopHome() { return <div className="desktopHome"><DesktopHeader/><main>
  <section className="deskHero deskShell" id="about"><img src="/ava.png" alt="Егор Трещев"/><div><h1>Егор Трещев</h1><p>Продуктовый дизайнер с опытом <strong>8+ лет</strong><br/>Сейчас в Альфа-Банке. Ex: Pinkman, Cs.Money, Mkws</p></div><a className="deskTelegram" href="https://t.me/yegortreschev" target="_blank" rel="noreferrer">Написать в телеграм</a></section>
  <section className="deskCases deskShell" id="work">{cases.map(item => <article key={item.image}><a href={item.href}><img className="deskCaseImage" src={`/portfolio/${item.image}`} alt=""/><div className="deskCaseCopy"><div><h2>{item.title}</h2></div><img className="deskCaseChevron" src="/chevron-right-medium.svg" alt="" aria-hidden="true"/></div></a></article>)}</section>
  <section className="deskConcepts deskShell" id="concepts"><h2>Концепты</h2><div className="conceptGrid">{conceptColumns.map((column, i) => <div key={i}>{column.map(image => <img key={image} src={`/portfolio/${image}`} alt=""/>)}</div>)}</div></section>
  <section className="deskHobbies deskShell" id="hobbies"><h2>Увлечения</h2><div className="hobbyLayout">
    <div className="hobbyLeft"><figure className="hob1"><img src="/portfolio/hob1.png" alt="Кофе на капоте автомобиля"/><figcaption>Обожаю кофе и веду про<br/>него уютный <a href="https://t.me/yegor_treschev" target="_blank" rel="noreferrer">телеграм-канал</a></figcaption></figure><figure className="hob4"><img src="/portfolio/hob5.png" alt="Книга Владимира Набокова"/><figcaption>Читаю и иногда пишу<br/>про книги на <a href="https://vc.ru/id818691" target="_blank" rel="noreferrer">vc</a> и <a href="https://dzen.ru/yegortreschev" target="_blank" rel="noreferrer">дзене</a></figcaption></figure></div><figure className="hob2"><img src="/portfolio/hob2.png" alt="Кофе и десерт"/></figure><figure className="hob3"><img src="/portfolio/hob3.png" alt="Егор играет в падел"/><figcaption>Играю в падел и бегаю</figcaption></figure><figure className="hob5"><img src="/portfolio/hob4.png" alt="Книга «Додо от подвала до миллиарда»"/></figure><figure className="hob6"><img src="/portfolio/hob6.png" alt="Кофейная станция"/></figure>
  </div></section>
  </main><footer className="deskFooter deskShell"><span>© Егор Трещев 2026</span><a href="https://t.me/yegortreschev" target="_blank" rel="noreferrer">Написать в телеграм</a></footer></div> }

function MobileHome() { return <div className="mobileHome"><header className="header"><div className="shell headerInner"><nav className="navGroup"><a href="#mobile-work">Кейсы</a><a href="#mobile-hobbies">Обо мне</a></nav><nav className="navGroup"><a href="/cv.pdf" download>Скачать CV</a><a href="https://t.me/yegortreschev" target="_blank" rel="noreferrer">Телеграм</a></nav></div></header><main><section className="hero shell" id="mobile-about"><img className="heroPortrait" src="/ava.png" alt="Егор Трещев"/><div className="heroTitle"><h1>Егор Трещев</h1><p>Продуктовый дизайнер в Альфа-Банке.<br/>Ex. Pinkman, Cs.Money, Mkws</p></div><a className="telegramButton" href="https://t.me/yegortreschev" target="_blank" rel="noreferrer">Написать в телеграм</a></section><section className="workSection shell" id="mobile-work"><div className="projects">{cases.map(item => <article className="project" key={item.image}><a href={item.href}><img className="projectImage" src={`/portfolio/${item.image}`} alt=""/><div className="projectCopy"><div><h3>{item.title}</h3></div><img className="projectChevron" src="/chevron-right-medium.svg" alt=""/></div></a></article>)}</div></section><section className="mobileConcepts shell" id="mobile-concepts"><h2>Концепты</h2><div className="mobileConceptGrid">{conceptColumns.flat().map(image => <img key={image} src={`/portfolio/${image}`} alt=""/>)}</div></section><section className="mobileHobbies shell" id="mobile-hobbies"><h2>Увлечения</h2><div className="mobileHobbyGrid"><figure><img src="/portfolio/hob1.png" alt="Кофе на капоте автомобиля"/><figcaption>Обожаю кофе и веду про него уютный <a href="https://t.me/yegor_treschev" target="_blank" rel="noreferrer">телеграм-канал</a></figcaption></figure><figure><img src="/portfolio/hob3.png" alt="Егор играет в падел"/><figcaption>Играю в падел и бегаю</figcaption></figure><figure><img src="/portfolio/hob5.png" alt="Книга Владимира Набокова"/><figcaption>Читаю и иногда пишу про книги на <a href="https://vc.ru/id818691" target="_blank" rel="noreferrer">vc</a> и <a href="https://dzen.ru/yegortreschev" target="_blank" rel="noreferrer">дзене</a></figcaption></figure><figure><img src="/portfolio/hob6.png" alt="Кофейная станция"/></figure></div></section></main><footer className="mobileFooter shell"><span>© Егор Трещев 2026</span><a href="https://t.me/yegortreschev" target="_blank" rel="noreferrer">Написать в телеграм</a></footer></div> }

export default function Home() { return <><DesktopHome/><MobileHome/></> }
